// <auto-generated />
namespace Preguntas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Token : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Token));
        
        string IMigrationMetadata.Id
        {
            get { return "201903111813041_Token"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
